#!/usr/bin/env bash
# Install nginx and start it
apt -y install nginx
systemctl start nginx
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.nginx-debian.html
systemctl restart nginx
