#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "
frontend
        bind 80 ssl crt /etc/ssl/certs/haproxy.pem
        default_backend web-backend
        option forwardfor

backend web-backend
        balance roundrobin
        server 11907-web-01 18.208.143.1 check
        server 11907-web-02 44.200.141.51 check
        " >> /etc/haproxy/haproxy.cfg
service haproxy restart
