#!/usr/bin/env bash
# install load balancer

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	sudo apt-get update -y -qq && \
		sudo apt-get install -y "$1" -qq
}

install haproxy #install haproxy

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://github.com/yuvenalmash/ permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
      server 453-web-01 35.243.128.200:80 check
      server 453-web-02 3.239.120.96:80 check
)"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
