#!/usr/bin/env bash
# Runs Nginx as user Nginx
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
echo ''
su nginx -s /bin/bash -c 'service nginx restart'
